[project]
name = "proyecto-optimizacion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Terrapin", email = "freq.modulada@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
    "networkx>=3.6.1",
    "numpy>=2.4.6",
    "ortools>=9.15.6755",
]

[project.scripts]
proyecto-optimizacion = "proyecto_optimizacion:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
